# Generated by Django 5.2.5 on 2025-09-01 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(blank=True, choices=[('technology', 'Technology'), ('financial services', 'Financial Services'), ('healthcare', 'Healthcare'), ('manufacturing', 'Manufacturing'), ('e commerce', 'E commerce'), ('education', 'Education'), ('real estate', 'Real Estate'), ('marketing', 'Marketing'), ('consulting', 'Consulting'), ('transportation', 'Transportation'), ('media', 'Media'), ('non-profit', 'Non-profit')], max_length=100, null=True)),
                ('company_size', models.CharField(blank=True, choices=[('(1–10 employees)', '(1–10 employees)'), ('(11–50 employees)', '(11–50 employees)'), ('(51–200 employees)', '(51–200 employees)'), ('(200+ employees)', '(200+ employees)')], max_length=100, null=True)),
                ('business_model', models.CharField(blank=True, choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('marketplace/platform', 'Marketplace/Platform'), ('agency/service provider', 'Agency/Service provider'), ('agency/service provider', 'Agency/Service provider')], max_length=100, null=True)),
                ('name', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('co-admin', 'Co-Admin'), ('owner', 'Owner')], max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
