# Generated by Django 5.2.5 on 2025-09-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_company_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(editable=False, max_length=12, null=True, unique=True),
        ),
    ]
